# Generated by Django <version> on <date> from <module>.

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Define any dependencies here, if there are any.
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                # Add other fields if necessary
            ],
        ),
    ]
