# Generated by Django 5.1 on 2024-08-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_delete_customuser_delete_uploadedimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User',
        ),
    ]
